# Generated by Django 4.2.5 on 2023-09-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ano_lanzamiento',
            field=models.IntegerField(null=True),
        ),
    ]
